name: 'Deploy to production (Vercel)'

on:
  workflow_dispatch:

env:
  PRE_PRODUCTION_HOST: 'https://test-vercel-org-pre-production.vercel.app'
  PRODUCTION_HOST: test-vercel-org-production.vercel.app
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_SCOPE: '1212evgen'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    environment:
      name: 'production'
      url: https://${{ env.PRODUCTION_HOST }}

    steps:
      - name: 'Setup Node.js v20'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install Vercel CLI'
        run: npm install --global vercel@33.2

      - name: 'Assign domains'
        run: vercel alias set ${{ env.PRE_PRODUCTION_HOST }} ${{ env.PRODUCTION_HOST }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }}
